apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
type: Opaque
stringData:
  {{ randAlphaNum 16 }}: {{ randAlphaNum 16 | quote }}
  {{ randAlphaNum 16 }}: {{ randAlphaNum 16 | quote }}