apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      port: {{ .Values.ports.api.servicePort }}
      targetPort: {{ .Values.ports.api.containerPort }}
    - name: logs
      port: {{ .Values.ports.logs.servicePort }}
      targetPort: {{ .Values.ports.logs.containerPort }}
    - name: soap
      port: {{ .Values.ports.soap.servicePort }}
      targetPort: {{ .Values.ports.soap.containerPort }}