apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
    helm.sh/chart: {{ include "spring-boot-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spring-boot-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: spring-boot-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--spring.profiles.active={{ .Values.profile }}"
          ports:
            - name: api
              containerPort: {{ .Values.ports.api.containerPort }}
            - name: logs
              containerPort: {{ .Values.ports.logs.containerPort }}
            - name: soap
              containerPort: {{ .Values.ports.soap.containerPort }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SECRET_KEY1
              valueFrom:
                secretKeyRef:
                  name: {{ include "spring-boot-api.fullname" . }}-secret
                  key: secretKey1
            - name: SECRET_KEY2
              valueFrom:
                secretKeyRef:
                  name: {{ include "spring-boot-api.fullname" . }}-secret
                  key: secretKey2
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          lifecycle:
            preStop:
              exec:
                command: ["wget", "http://localhost:8080/service/shutdown"]
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "spring-boot-api.fullname" . }}-config
