apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-api.fullname" . }}
                port:
                  number: {{ .Values.ports.api.servicePort }}
          - path: /logs
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-api.fullname" . }}
                port:
                  number: {{ .Values.ports.logs.servicePort }}
          - path: /soap
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-api.fullname" . }}
                port:
                  number: {{ .Values.ports.soap.servicePort }}
